apiVersion: fission.io/v1
kind: Package
metadata:
  name: fibonacci-pkg
  namespace: default
spec:
  environment:
    name: python
    namespace: default
  source:
    literal: |
      def main():
          return "Hello, World!"
