apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: fission
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      function: fibonacci
  delay:
    latency: "50ms"
  duration: "10s"
  scheduler:
    cron: "0 5 * * *" # At 5 minutes past the hour

