apiVersion: v1
kind: Service
metadata:
  name: fibonacci-backend
spec:
  selector:
    app: fibonacci
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: fibonacci:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000