apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: kube-system
data:
  registries.yaml: |
    unqualified-search-registries = ["docker.io"]
    [[registry]]
    prefix = "localhost:5000"
    insecure = true
    location = "localhost:5000"